#!/usr/bin/env python3
"""
cluster-notes.py — Phase 1 of the Community Report Generator.
Reads NoteEmbeddings from the vault DB, runs k-means clustering,
and writes cluster membership files to 01_Wiki/community-reports/.

Usage:
    python 02_System/cluster-notes.py [--k 8] [--db path/to/wiki.db]
"""
import argparse, json, os, sqlite3
from pathlib import Path

import numpy as np
from sklearn.cluster import KMeans

VAULT_ROOT = Path(__file__).parent.parent
DEFAULT_DB = VAULT_ROOT / "00_Raw/PoShWiKi/wiki.db"
REPORTS_DIR = VAULT_ROOT / "01_Wiki/community-reports"

def load_embeddings(db_path: str) -> tuple[list[str], np.ndarray]:
    """Return (note_names, embeddings_matrix) for all active notes."""
    conn = sqlite3.connect(db_path)
    rows = conn.execute(
        "SELECT NoteName, Embedding FROM NoteEmbeddings ORDER BY NoteName"
    ).fetchall()
    conn.close()
    names = [r[0] for r in rows]
    vecs  = np.array([json.loads(r[1]) for r in rows], dtype=np.float32)
    # L2-normalize for cosine similarity
    norms = np.linalg.norm(vecs, axis=1, keepdims=True)
    vecs  = vecs / np.where(norms == 0, 1, norms)
    return names, vecs

def estimate_k(vecs: np.ndarray, k_range=range(4, 16)) -> int:
    """Elbow method: pick k where inertia improvement drops below 10%."""
    inertias = []
    for k in k_range:
        km = KMeans(n_clusters=k, random_state=42, n_init=10)
        km.fit(vecs)
        inertias.append(km.inertia_)
    for i in range(1, len(inertias)):
        if inertias[i-1] > 0:
            improvement = (inertias[i-1] - inertias[i]) / inertias[i-1]
            if improvement < 0.10:
                return list(k_range)[i]
    return list(k_range)[-1]

def write_cluster_report(cluster_id: int, member_names: list[str], output_dir: Path):
    """Write a Level-1 cluster membership file in community-report-generator format."""
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / f"cluster-{cluster_id:02d}-members.md"
    lines = [
        f"---",
        f"title: 'Cluster {cluster_id:02d} — Members (Level-1)'",
        f"author: gemini-cli",
        f"date: '{__import__('datetime').date.today()}'",
        f"status: active",
        f"type: community",
        f"cluster_id: 'cluster-{cluster_id:02d}'",
        f"level: 1",
        f"member_count: {len(member_names)}",
        f"aliases:",
        f"  - cluster-{cluster_id:02d}",
        f"---",
        f"",
        f"# Cluster {cluster_id:02d} — Member Notes",
        f"",
        f"*This file was generated by `02_System/cluster-notes.py`. Feed to Claude Summarizer for [[community-report-generator]] Phase 2.*",
        f"",
        f"## Members ({len(member_names)} notes)",
        f"",
    ]
    for name in sorted(member_names):
        lines.append(f"- [[{name}]]")
    lines += ["", "## References", "- [[community-report-generator]]", ""]
    path.write_text("\n".join(lines), encoding="utf-8")
    return path

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--k",   type=int, default=0,
                        help="Number of clusters (0 = auto-detect via elbow method)")
    parser.add_argument("--db",  default=str(DEFAULT_DB))
    args = parser.parse_args()

    print(f"Loading embeddings from {args.db}...")
    names, vecs = load_embeddings(args.db)
    print(f"  {len(names)} notes loaded.")

    k = args.k if args.k > 0 else estimate_k(vecs)
    print(f"  Using k={k} clusters.")

    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(vecs)

    clusters: dict[int, list[str]] = {}
    for name, label in zip(names, labels):
        clusters.setdefault(label, []).append(name)

    print(f"\nCluster sizes:")
    for cid, members in sorted(clusters.items(), key=lambda x: -len(x[1])):
        print(f"  Cluster {cid:02d}: {len(members)} notes")

    print(f"\nWriting membership files to {REPORTS_DIR}/...")
    for cid, members in clusters.items():
        path = write_cluster_report(cid, members, REPORTS_DIR)
        print(f"  Written: {path.name}")

    print(f"\nDone. Run Claude Summarizer on each cluster file for Phase 2.")

if __name__ == "__main__":
    main()
