<#
.SYNOPSIS
    Tool Registry Generator
.DESCRIPTION
    Scans 02_System/ for .ps1 files, extracts help metadata, and generates a machine-readable TOOL_REGISTRY.md for agents.
.EXAMPLE
    pwsh -NoProfile -ExecutionPolicy Bypass -File 02_System/generate-tool-registry.ps1
#>

$systemPath = "02_System"
$outputPath = "02_System/TOOL_REGISTRY.md"
$scripts = Get-ChildItem -Path $systemPath -Filter "*.ps1"

function Convert-RegistrySafeText {
    param(
        [Parameter(Mandatory = $true)]
        [string]$Text
    )

    $normalized = ($Text -replace "`r`n", ' ') -replace "`n", ' '
    $normalized = $normalized -replace '\[\[([^\]|]+)\|([^\]]+)\]\]', '$2'
    $normalized = $normalized -replace '\[\[([^\]]+)\]\]', '$1'
    $normalized = $normalized -replace '\s+', ' '
    return $normalized.Trim()
}

$registryContent = @"
# Vault Tool Registry (Agent Optimized)

This document provides a machine-readable index of the system utilities available in this vault.

"@

foreach ($script in $scripts) {
    # Use Get-Help to extract structured data
    $help = Get-Help $script.FullName -ErrorAction SilentlyContinue
    
    if ($help -and $help.Synopsis) {
        $synopsis = Convert-RegistrySafeText -Text $help.Synopsis
        $description = if ($help.Description.Text) { Convert-RegistrySafeText -Text ($help.Description.Text -join ' ') } else { "No description provided." }
        $inputs = if ($help.Inputs.inputTypeName.Text) { ($help.Inputs.inputTypeName.Text | ForEach-Object { $_.Trim() }) -join ', ' } else { "None" }
        $outputs = if ($help.Outputs.outputTypeName.Text) { ($help.Outputs.outputTypeName.Text | ForEach-Object { $_.Trim() }) -join ', ' } else { "None" }

        $registryContent += "## $synopsis`n"
        $registryContent += "*   **File:** ``$($script.FullName.Replace('C:\Users\executor\Documents\vulture-nest\', ''))`` `n"
        $registryContent += "*   **Description:** $description`n"
        $registryContent += "*   **Command:** ``pwsh -NoProfile -ExecutionPolicy Bypass -File $($script.Name)`` `n"
        $registryContent += "*   **Inputs:** $inputs`n"
        $registryContent += "*   **Outputs:** $outputs`n`n"
    } else {
        Write-Warning "No help metadata found for $($script.Name). Please add .SYNOPSIS and .DESCRIPTION blocks."
    }
}

$registryContent += "---`n*Generated by generate-tool-registry.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')*"

Set-Content -Path $outputPath -Value $registryContent -Encoding utf8
Write-Host "Tool Registry generated at $outputPath" -ForegroundColor Green
